FROM debian

RUN apt-get update  \
    && apt-get upgrade  \
    && apt-get -y install python-is-python3 \
                          python3-pip \
                          python3-cffi \
                          python3-brotli \
                          libpango-1.0-0 \
                          libharfbuzz0b \
                          libpangoft2-1.0-0 \
                          curl \
                          chromium \
    && pip install mkdocs \
                   weasyprint \
                   mkdocs-with-pdf \
                   mkdocs-mermaid2-plugin
