site_name: MkLorum
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md

theme:
  name: material

plugins:
  - search 
  - mermaid2 
  - mermaid-export-to-svg:
        export_to_pdf: true
        debug: true
    
  - with-pdf
#        use_relaxed_js_renderer: true
#        render_js: true
#        headless_chrome_path: chromium
#      debug_html: true